In [2]:
## How do you calculate the dot product of two NumPy arrays?
import numpy as np 
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

np.dot(arr1,arr2)

20

## What is the difference between a shallow copy and deep copy in Numpy ?
In numPy we have two ways to copy an array. shallow copy and deep copy are two most used methods used in numpy to copy an array. Here is the main difference between both of them.

Shallow copy
A shallow copy is a new array that is a view of the original array's data.

The new array is referencing the same data as the original array, so there's actually no duplication happening.

Changes made in the original array will also be reflected in the shallow copy, and vice versa.

Deep copy

A deep copy is a completely new and independent array that does not share any data with the original array.

The data is duplicated, creating a separate copy in memory.

Changes made in the original array do not affect the deep copy, and vice versa.

In [9]:
## How do you reshape a NumPy array?
arr = np.array([1,2,3,4,5,6])
arr_reshaped = arr.reshape(2,3)
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
## How to perform element-wise operations on NumPy arrays?

np.add(arr1,arr2)

array([3, 5, 7])

In [16]:
arr1-arr2

array([-1, -1, -1])

In [17]:
## Define the var function in NumPy.

#In NumPy, the var function is used to compute the variance of elements in an array or along a specified axis. Variance is a measure of the spread or dispersion of data points.

np.var(arr)

2.9166666666666665

In [19]:
# How to generate random numbers with NumPy?

random_float = np.random.rand()
random_integer = np.random.randint(5)

In [21]:
## How can you create a NumPy array from a Python list?

python_list = [1, 2, 3, 4, 5]

numpy_array = np.array(python_list)
numpy_array

array([1, 2, 3, 4, 5])

In [22]:
## How can you concatenate two NumPy arrays vertically?

array_vertical = np.concatenate((arr1,arr2), axis = 0)
array_vertical

array([1, 2, 3, 2, 3, 4])

## How can you generate random numbers following a normal distribution using NumPy?
We can generate random numbers following a normal distribution (Gaussian distribution) using NumPy's random module. NumPy provides several functions for this purpose, with different options for specifying the mean and standard deviation of the distribution. The most commonly used function is numpy.random.normal.

In [24]:
# Generate 5 random numbers from a normal distribution with mean 0 and std dev 1
samples = np.random.normal(loc=0, scale=1, size=5)

"""
loc: Mean of the distribution (default is 0)

scale: Standard deviation (default is 1)

size: Number or shape of the output array (e.g., 5, (2, 3), etc.)
"""

'\nloc: Mean of the distribution (default is 0)\n\nscale: Standard deviation (default is 1)\n\nsize: Number or shape of the output array (e.g., 5, (2, 3), etc.)\n'

In [26]:
## Convert a multidimensional array to 1D array.

md_array = np.array([[2,3,4],[4,6,7],[1,4,6]])

one_dim_Array = md_array.flatten()

one_dim_Array

array([2, 3, 4, 4, 6, 7, 1, 4, 6])

## How can you identify outliers in a NumPy array?

Identifying and removing outliers in a NumPy array involves several steps. Outliers are data points that significantly deviate from the majority of the data and can adversely affect the results of data analysis. Here's a general approach to identify and remove outliers:

Identifying Outliers:

Calculate Descriptive Statistics: Compute basic statistics like the mean and standard deviation of the array to understand the central tendency and spread of the data.
Define a Threshold:
Decide on a threshold where data points are considered outliers.

In [27]:
## How would you convert a pandas dataframe into NumPy array.

import pandas as pd 
import numpy as np 

data = {'A': [10,20,30], 'B': [20,30,40]}

df = pd.DataFrame(data)

numpy_array = df.values

numpy_array

array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int64)

## What are some common techniques for normalizing data in a NumPy array?
Data analysis and machine learning frequently utilize normalization, a preprocessing method, to scale data to a standard range, usually between 0 and 1, or with a mean of 0 and a standard deviation of 1. Many machine learning algorithms can perform better with the aid of normalized data, which also ensures that features with various scales contribute equally to the study.

Some common technique are:

Min-Max Scaling
Z-Score Normalization (Standardization)
Log Transformation
Box-Cox Transformation
Robust Scaling


## What distinguishes np.mean() from np.average() in NumPy?

np.mean() and np.average() in NumPy both calculate the mean of an array, but np.average() allows for the use of weights. While np.mean() treats all elements equally, np.average() considers weights assigned to each element, providing a weighted average when specified. This makes np.average() more flexible for situations where certain elements contribute more or less to the overall average based on their assigned weights. 

Here are examples illustrating the use of np.mean() and np.average() in NumPy: 

In [28]:
#Write a NumPy program to extract a subarray from a larger array based on given slicing parameters.

In [29]:
#Generate a 2D array F of shape (5, 5) with random integer values between 1 and 100. Compute the mean and standard deviation for each row and each column separately using NumPy functions. 

['abdfjhb', 'kjgsdf']